### ISSUE TITLE
QA Liquidityd Client CLI Documentation

### ISSUE THREAD

**Issue by SenorMonito** [tendermint/liquidity#177]
The purpose of this review is to review the CLI documentation for the Liquidity Module. This includes

- Review the CLI documentation via --help flag
- Instead of making suggestions to the [markdown documentation](https://github.com/tendermint/liquidity/blob/develop/doc/client.md), Dongsam helped Barrie install the liquidityd app. Barrie ran the commands (yay) and edited the go files in https://github.com/tendermint/liquidity/pull/212 

Outcomes will include
- Edits directly in PR https://github.com/tendermint/liquidity/pull/212
- Comments that outline areas for improvements and identify 
- It may also include plans for remediation and how to write better documentation

**Comment by barriebyron** [comment]
@SenorMonito I worked with Dongsam so that I was set up to run the commands and gain more context on how the parameters and flags work. I think we still have work to do (I need help understanding where all the flags are documented for each command, I'd like to see flag descriptions with the CLI help). 

I provided direct edits to the commands in:

- x/liquidity/client/cli/query.go
- x/liquidity/client/cli/tx.go

Editorial suggestions and resources are provided for each change, highlights include:
- use present tense https://developers.google.com/style/tense 
- omit please, see https://developers.google.com/style/tone#politeness-and-use-of-please 
- avoid "we" and "the user" and instead use second person "you", see https://developers.google.com/style/person 
   For example, instead of "User must create..." r/w as "Create liquidity pools..." 
- omit "current" since the command is always current
- do not specify flags in the command description; omit "for the specified... <whatever" from the command descriptions, the flags and parameters handle that logic
- omit mention of future versions or features, see https://developers.google.com/style/future 
- error messages identify what's wrong, add details and descriptions of what values are expected 
- for numbers and money, use less than and greater than instead of cheaper than and more than

I'll be expecting some back and forth since I am guessing at some of the technical bits. Let me know how I am doing!

**Comment by barriebyron** [comment]
moving notes from Slack to this PR so I remember them:
- For edits, do not make changes to the `client.md` file. Instead, make changes edits to the description of CLI directly in go file, like `x/liquidity/client/cli/query.go ` and `x/liquidity/client/cli/tx.go`

what other go files require my attention?

**Comment by barriebyron** [comment]
@dongsam did the changes suggested in https://github.com/tendermint/liquidity/pull/212/files#diff-8d365b17c7a0d6745216f28bcbf704122d6d0fd7a4338cca9edb8a6c335cb137R6 make it into the code? (even though the suggestions were to the generated client.md file and not the source go files?

**Comment by dongsam** [comment]
> @dongsam did the changes suggested in https://github.com/tendermint/liquidity/pull/212/files#diff-8d365b17c7a0d6745216f28bcbf704122d6d0fd7a4338cca9edb8a6c335cb137R6 make it into the code? (even though the suggestions were to the generated client.md file and not the source go files?

Sure, the changes suggested in https://github.com/tendermint/liquidity/pull/212/files#diff-8d365b17c7a0d6745216f28bcbf704122d6d0fd7a4338cca9edb8a6c335cb137R6 is applied and merged into the `x/liquidity/client/cli/tx.go`, `x/liquidity/client/cli/query.go`, Thanks @barriebyron  

And I just open new PR https://github.com/tendermint/liquidity/pull/234 for continuous
