### ISSUE TITLE
Caution on Using Strict Equality Check

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#392]
## Summary

> where swapFee is set to 0.3%. The computation on the right hand side is done using the function GetOfferCoinFee. Since it involves a division and a multiplication operation, there might be a negligible precision loss. In the event of a precision loss, the input OfferCoinFee from the user might not precisely match the right hand side, leading to an unexpected error. In general, equality checks with division operations on one of the sides must be avoided. Instead, the differences between the two sides must be ensured to be negligibly small.

https://github.com/tendermint/liquidity/blob/develop/x/liquidity/keeper/liquidity_pool.go#L770-L772

Avoid using strict equality is very important because we have lots of decimal truncation processes in our codebase. We need to find this in entire codebase and improve it

After truncation, we don't see any risk of failure of equality check if the user frontend calculate right. Hence we don't change this. But we will search other codebase location where we used strict equality, and review possible problems.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by lukerhoads** [comment]
Would this be an example

```golang
if !afterReserveCoinA.Equal(lastReserveCoinA.Add(depositCoinA)) ||
  !afterReserveCoinB.Equal(lastReserveCoinB.Add(depositCoinB)) {
  panic("invariant check fails due to incorrect deposit amounts")
}
```

**Comment by hallazzang** [comment]
@lukerhoads Actually we need to strictly check the change there, because if it differs even a little, it means that there's an inconsistency in sending coins between accounts.
Here's an example code from the original issue: https://github.com/tendermint/liquidity/blob/01a2f019e1bbc83f0e1b68034d312431a90aa803/x/liquidity/keeper/liquidity_pool.go#L799
Because the `OfferCoinFee` is calculated by multiplying `sdk.Dec`(currently `"0.0015"`) and `sdk.Int`, there might be a decimal precision issue and of course a decimal truncation error.
This kind of potential errors are what we should review.

**Comment by hallazzang** [comment]
It seems that there is no other places where the strict equality check would be an issue.
For the `OfferCoinFee`, currently it doesn't seem to cause a problem, but later we could accept offer coin fees higher than the required amount.
